<?php
/**
 * TL_ROOT/system/modules/formrecipients/languages/fr/modules.php 
 * 
 * Contao extension: formrecipients 1.0.0 rc1 
 * French translation file 
 * 
 * Copyright : (C) 2013 Enisseo  
 * License   : LGPL 
 * Author    : Nicolas Raynaud (enisseo), http://www.enisseo.net 
 * Translator: Nicolas Raynaud (enisseo), http://www.enisseo.net 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['formrecipients']['0'] = "Destinataires d'un formulaire";
$GLOBALS['TL_LANG']['MOD']['formrecipients']['1'] = "Fournit un élément de formulaire pour que l'utilisateur puisse choisir à qui envoyer les données.";
 
?>
