<?php
/**
 * TL_ROOT/system/modules/lexformrecipients/languages/fr/tl_form_field.php 
 * 
 * Contao extension: formrecipients 1.0.0 rc1 
 * French translation file 
 * 
 * Copyright : (C) 2013 Enisseo  
 * License   : LGPL 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FFL']['recipients']['0'] = "Destinataires";
$GLOBALS['TL_LANG']['FFL']['recipients']['1'] = "Une liste des différents destinataires possibles.";
$GLOBALS['TL_LANG']['tl_form_field']['recipients_legend'] = "Options d'envoi";?>